/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify Delegates.tt instead *
 *************************************************************************/

namespace ChaosDbg.Detour
{
    internal static class Delegates
    {
    }
}
